[package]
name = "md-toc"
version = "0.1.0"
authors = ["Richard Jones <richard.jones@reece.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
